version: "3"
services:
  api:
    container_name: api
    build: .
    ports:
      - 3000:80
    volumes:
      - ./app:/app
    depends_on:
      - redis
    env_file: ./app/.env
    restart: $RESTART
    command: $COMMAND

  redis:
    container_name: redis
    image: redis:alpine
    ports:
      - 6379:6379
    restart: always
